version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps/spllit-backend #where to store the artifacts
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
  - object: /bin/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
hooks:
  ApplicationStop:
    - location: bin/stop_server.sh #stop script for the website
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: bin/start_server.sh #start script for the backend server
      timeout: 300
      runas: ubuntu