version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps/spllit-backend #where to store the artifacts
permissions:
  - object: /home/ubuntu/apps/spllit-backend
    owner: ubuntu
    mode: 755
    type: directory
hooks:
  ApplicationStart:
    - location: bin/start_servers.sh #start script for the website
      timeout: 300
      runas: ubuntu